
NDefines.NMilitary.DEFAULT_WARGOAL_BATTLESCORE_BONUS = 7
NDefines.NMilitary.WARSCORE_MAX_FROM_BATTLES = 75
NDefines.NMilitary.BASE_MP_TO_MANPOWER = 0.05
NDefines.NMilitary.MERCENARY_BASE_COST = 40
NDefines.NMilitary.INFANTRY_COST = 30
NDefines.NMilitary.CAVALRY_COST = 60
NDefines.NMilitary.ARTILLERY_COST = 120

NDefines.NGame.RNW_MERC_COMPANY_DEV_FACTOR_MIN = 0.0025
NDefines.NGame.RNW_MERC_COMPANY_DEV_FACTOR_MAX = 0.01
